### ISSUE TITLE
Border Reset issues

### ISSUE THREAD

**Issue by Astolate** [BentoBoxWorld/Border#144]
### Expected behavior

When you reset borders it should change the protection to 20.

### Observed/Actual behavior

Reseting borders is not making it 20 it's making it 45 for some reason however it places the border AT 20. When players attempt to push their island back out to the range through upgrades the border will not push out as far as it is supposed to meaning they don't have access to their max island size (there is about 25 blocks they can't push it.)

### Steps/models to reproduce

Have players fully upgrade islands using ob upgrade, reset island range.

### BentoBox version

2.7.0

### Other

![image](https://github.com/user-attachments/assets/0f362462-b681-47fe-a4e4-7b50968e8cee)

**Comment by Astolate** [comment]
![image](https://github.com/user-attachments/assets/da6d6ff9-395a-44fc-9f59-556a3e967969)
it seems it's also not removing the barrier blocks, leaving behind ghost blocks when the barrier is moved and you're using barrier type. Barrier shows correctly when using barrier type - shows wrong when using vanilla type.

**Comment by tastybento** [comment]
This bug was fixed in later versions of BentoBox. The range wasn't benign set correctly when using upgrades.

**Comment by Astolate** [comment]
> This bug was fixed in later versions of BentoBox. The range wasn't benign set correctly when using upgrades.

We can't use newer versions of Bentobox due to our server version - is this is a bentobox issue then? Can we update aoneblock to fix it?

**Comment by tastybento** [comment]
Can you share the output of /box version, so I can see exactly what you are running?

**Comment by Astolate** [comment]
![Image](https://github.com/user-attachments/assets/0509a9a0-88ce-4937-87f1-f194b087160b)

Also having issues now where player islands borders are randomly shrinking to 0 range

**Comment by Astolate** [comment]
Any updates? Still having this issue and when players upgrade island with ob upgrade they can't actually build in the range given.

**Comment by tastybento** [comment]
If you cannot update BentoBox, then you need to use an older version of Upgrades that doesn't use the latest API, which would be [build 138](https://ci.codemc.io/job/BentoBoxWorld/job/Upgrades/138/). (See https://github.com/BentoBoxWorld/Upgrades/issues/59).

Unfortunately, I don't have time to back-port fixes to older versions, so this is the best workaround right now. Bugs are always being fixed, but I only have the bandwidth to make them work on the latest versions of MC, Paper, etc.

**Comment by Astolate** [comment]
> If you cannot update BentoBox, then you need to use an older version of Upgrades that doesn't use the latest API, which would be [build 138](https://ci.codemc.io/job/BentoBoxWorld/job/Upgrades/138/). (See [BentoBoxWorld/Upgrades#59](https://github.com/BentoBoxWorld/Upgrades/issues/59)).
> 
> Unfortunately, I don't have time to back-port fixes to older versions, so this is the best workaround right now. Bugs are always being fixed, but I only have the bandwidth to make them work on the latest versions of MC, Paper, etc.

I appreciate it, I'll check and see if this works as a solution and if so that's good enough for me!
